EigenInclude		:= 

LibMeshInclude		:= /usr/local/include/libmesh
LibMeshLibPath 	:= /usr/local/lib

JacobiPolInclude	:= /home/soblinsky/pacsProject/jacobi_polynomial
JacobiPolDir		:= /home/soblinsky/pacsProject/jacobi_polynomial
JacobiPolLibFile	:= $(JacobiPolDir)/jacobi_polynomial.o

SandiaRuleInclude	:= /home/soblinsky/MySoftware/sandia_rules
SandiaRuleDir		:= /home/soblinsky/MySoftware/sandia_rules
SandiaRuleLibFile	:= $(SandiaRuleDir)/sandia_rules.o

#TODO: add the option to insert here flags to pass to the preprocessor and/or compiler and/or linker
